// Mapeo de columna frontend → campo sort backend (Monitor de Precios)
export const SORT_FIELD_MAP: Record<string, string> = {
    sku: "sku",
    mla: "mla",
    tituloDux: "tituloDux",
    canalNombre: "canal",
    cuotasDescripcion: "cuotas",
    costo: "costoproducto",
    iva: "iva",
    pvp: "pvp",
    pvpInflado: "pvpinflado",
    ganancia: "ganancia",
    costosVenta: "costosventa",
    ingresoNetoVendedor: "ingresonetovendedor",
    margenSobrePvp: "margensobrepvp",
    margenSobreIngresoNeto: "margensobreingreso",
    markupPorcentaje: "markup",
    margenMinorista: "margenminorista",
    margenMayorista: "margenmayorista",
    precioInfladoCodigo: "precioInflado",
    fechaUltimoCosto: "fechaultimocosto",
    fechaUltimoCalculo: "fechaultimocalculo",
};
